import { MetadataRoute } from "next";

/**
 * Generates the dynamic `robots.txt` configuration for search engine crawlers and web spiders.
 *
 * @description Defines per-user-agent crawler policies, allowlists, disallowlists, crawl delays,
 * canonical sitemap URL, and host directives to optimize indexing and secure private/internal routes.
 *
 * @returns {MetadataRoute.Robots} The typed Robots configuration object for Next.js metadata route generation.
 */
export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || "https://infinitedim.dev";

  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/projects",
          "/skills",
          "/about",
          "/contact",
          "/blog",
          "/sitemap.xml",
          "/robots.txt",
        ],
        disallow: [
          "/api/",
          "/admin/",
          "/private/",
          "/s3cr3t/",
          "/gate",
          "/gate/",
          "/terminal",
          "/terminal/",
          "/_next/",
          "/sw.js",
          "*.json$",
          "/temp/",
          "/draft/",
          "/test/",
          "/dev/",
          "/staging/",
        ],
        crawlDelay: 1,
      },
      {
        userAgent: "Googlebot",
        allow: ["/", "/projects", "/skills", "/about", "/contact", "/blog"],
        disallow: [
          "/api/",
          "/admin/",
          "/private/",
          "/gate",
          "/gate/",
          "/terminal",
          "/terminal/",
          "/_next/",
          "/sw.js",
          "*.json$",
        ],
        crawlDelay: 1,
      },
      {
        userAgent: "Googlebot-Image",
        allow: ["/", "/projects", "/images/", "/og-image.png", "/avatar.jpg"],
        disallow: ["/api/", "/admin/", "/private/", "/_next/", "/sw.js"],
        crawlDelay: 1,
      },
      {
        userAgent: "Googlebot-Mobile",
        allow: ["/", "/projects", "/skills", "/about", "/contact", "/blog"],
        disallow: [
          "/api/",
          "/admin/",
          "/private/",
          "/gate",
          "/gate/",
          "/terminal",
          "/terminal/",
          "/_next/",
          "/sw.js",
          "*.json$",
        ],
        crawlDelay: 1,
      },
      {
        userAgent: "Bingbot",
        allow: ["/", "/projects", "/skills", "/about", "/contact", "/blog"],
        disallow: [
          "/api/",
          "/admin/",
          "/private/",
          "/gate",
          "/gate/",
          "/terminal",
          "/terminal/",
          "/_next/",
          "/sw.js",
          "*.json$",
        ],
        crawlDelay: 1,
      },
      {
        userAgent: "Slurp",
        allow: ["/", "/projects", "/skills", "/about", "/contact", "/blog"],
        disallow: [
          "/api/",
          "/admin/",
          "/private/",
          "/gate",
          "/gate/",
          "/terminal",
          "/terminal/",
          "/_next/",
          "/sw.js",
          "*.json$",
        ],
        crawlDelay: 1,
      },
      {
        userAgent: "DuckDuckBot",
        allow: ["/", "/projects", "/skills", "/about", "/contact", "/blog"],
        disallow: [
          "/api/",
          "/admin/",
          "/private/",
          "/gate",
          "/gate/",
          "/terminal",
          "/terminal/",
          "/_next/",
          "/sw.js",
          "*.json$",
        ],
        crawlDelay: 1,
      },
      {
        userAgent: "GPTBot",
        allow: ["/blog", "/blog/"],
        disallow: ["/"],
      },
      {
        userAgent: "CCBot",
        allow: ["/", "/projects", "/skills", "/about", "/contact", "/blog"],
        disallow: [
          "/api/",
          "/admin/",
          "/private/",
          "/gate",
          "/gate/",
          "/terminal",
          "/terminal/",
          "/_next/",
          "/sw.js",
          "*.json$",
        ],
        crawlDelay: 10,
      },
      {
        userAgent: "AhrefsBot",
        allow: ["/", "/projects", "/skills", "/about", "/contact", "/blog"],
        disallow: [
          "/api/",
          "/admin/",
          "/private/",
          "/gate",
          "/gate/",
          "/terminal",
          "/terminal/",
          "/_next/",
          "/sw.js",
          "*.json$",
        ],
        crawlDelay: 10,
      },
      {
        userAgent: "SemrushBot",
        allow: ["/", "/projects", "/skills", "/about", "/contact", "/blog"],
        disallow: [
          "/api/",
          "/admin/",
          "/private/",
          "/gate",
          "/gate/",
          "/terminal",
          "/terminal/",
          "/_next/",
          "/sw.js",
          "*.json$",
        ],
        crawlDelay: 10,
      },
      {
        userAgent: "MJ12bot",
        allow: ["/", "/projects", "/skills", "/about", "/contact", "/blog"],
        disallow: [
          "/api/",
          "/admin/",
          "/private/",
          "/gate",
          "/gate/",
          "/terminal",
          "/terminal/",
          "/_next/",
          "/sw.js",
          "*.json$",
        ],
        crawlDelay: 10,
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  };
}
